OKHWR.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OKHWR.Web.Controllers
{
  public class HomeController : Controller
  {
    //
    // GET: /Home/

    public ActionResult Index()
    {
      return View();
    }

  }
}

OKHWR.Web/Controllers/RecognitionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using OKHWR.Common.Common;
using OKHWR.Shape.Reco;
using OKHWR.Web.Init;

namespace OKHWR.Web.Controllers
{
  public class RecognitionController : Controller
  {
    //
    // GET: /KhmerHandWritingRecognition/

    public ActionResult Index()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Recognize(TraceGroup strokes)
    {
      //var aa = strokes.ToString();
      //var serializer = new JavaScriptSerializer();
      //var originalObject = serializer.Deserialize<TraceGroup>(strokes.ToString());
      var recognizer = RecognizerContext.GetNNRecognizer;
      var result = recognizer.Recognize(strokes);
      return Json(result, JsonRequestBehavior.AllowGet);

    }
  }
}

OKHWR.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Khmer Text";
}

<h2>Online Handwriting Recognition for Khmer Characters</h2>

Now you are able to do hand writing recognition for Khmer character.

<a href="@Url.Action("Index", "Recognition")">Try our Demo Now</a>

OKHWR.Web/Views/Recognition/Index.cshtml
@{
    ViewBag.Title = "Online Khmer Hand Writing Recognition";
}

<h2>Demo on Online Khmer Character Hand Writing Recognition</h2>
Draw Khmer Characters in the Canvas

<div id="place">
  <div id="draw-area">
  <div id="drawkhmer-char-canvas" class="drawkhmer-canvas"></div>
  <div id="found-khmer-char"></div>
  </div>
  <div id="drawkhmer-desc">Once you draw on the canvas, the result will come out with confidence level. The more confidence value, the more likely character would be.</div>
  <div style="clear: both"></div>
  <input type="checkbox" id="show-numbers" checked="checked" /><label for="show-numbers">Show stroke numbers</label>
  <div>
    <!--<input id="drawkhmer-clear-button" type="button" value="Clear everything" />-->
    <a id="drawkhmer-clear-button" href="#" class="btn-violet">Clear</a>
    <a id="drawkhmer-back-line-button" href="#" class="btn-violet">Remove Last Stroke</a>
    <!--<input id="drawkhmer-back-line-button" type="button" value="Remove last stroke" />-->
  </div>
</div>


@section scripts{
  <link href="@Url.Content("~/Content/writing/draw.css")" rel="stylesheet" type="text/css" />
  <link href="@Url.Content("~/Content/writing/khmer-reco.css")" rel="stylesheet" type="text/css" />
  <script src="@Url.Content("~/Scripts/writing/draw-13.js")" type="text/javascript"></script>
  <script src="@Url.Content("~/Scripts/writing/kudo-13.js")" type="text/javascript"></script>
  <!--<script src="@Url.Content("~/Scripts/writing/kanji-13.js")" type="text/javascript"></script>-->
}

<script language="javascript" type="text/javascript">
  $(document).ready(function () {
    drawkhmer_onload();
  });
</script>

OKHWR.Web/Views/Recognition/Recognize.cshtml
@{
  Layout = null;
    ViewBag.Title = "Recognize";
}

<h2>Recognize</h2>

OKHWR.Web/Views/Shared/_Header.cshtml
@{
  Layout = null;
}

<a href="@Url.Action("Index", "Home")">
  <div id="logo">អក្សរ​ខ្មែរ</div>Khmer Text</a>



OKHWR.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
    <link href='http://fonts.googleapis.com/css?family=Hanuman' rel='stylesheet' type='text/css'>
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-18548170-3']);
      _gaq.push(['_setDomainName', 'khmertext.com']);
      _gaq.push(['_trackPageview']);

      (function () {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

   </script>
</head>

<body>
  <div id="main">
    <div id="header-wrapper">
      <div id="header">@Html.Partial("_Header")</div>
    </div>
    <div class="header-shadow"></div>
    <div id="content-wrapper">
      <div id="content" class="content round">
      @RenderBody()
      </div>
    </div>
    <div id="foot-wrapper">
      <div id="footer">
        Copyright (c) 2012 <a href="@Url.Action("Index","Home")">KhmerText.com</a>. All rights reserved.
      </div>
    </div>
  </div>
    @if (IsSectionDefined("scripts"))
    {
	    @RenderSection("scripts");
    }
</body>
</html>